apiVersion: v1
kind: Service
metadata:
  name: solid-vite
  namespace: solid-vite
  labels:
    app: solid-vite
spec:
  type: ClusterIP
  selector:
    app: solid-vite
  ports:
  - port: 80
    targetPort: 5173
    protocol: TCP
    name: http
